version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: auth_postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test1234
      POSTGRES_DB: authdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  auth:
    build: ./backend/auth
    container_name: auth_service
    env_file:
      - ./backend/auth/.env
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  user:
    build: ./backend/user
    container_name: user_service
    env_file:
      - ./backend/user/.env
    ports:
      - "8081:8081"
    depends_on:
      - postgres

  schedule:
    build: ./backend/schedule
    container_name: schedule_service
    env_file:
      - ./backend/schedule/.env
    ports:
      - "8082:8082"
    depends_on:
      - postgres

  appointment:
    build: ./backend/appointment
    container_name: appointment_service
    env_file:
      - ./backend/appointment/.env
    ports:
      - "8083:8083"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - auth
      - appointment
      - schedule
      - user
    restart: unless-stopped

volumes:
  pgdata: